import numpy as np
import onnx
import onnxruntime as ort
import sys
import os

# Get the absolute path to the script's directory
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# =============== Import Utility Functions ===============
from src.onnx_utils import max_abs_error, snr_db

# ==== Loading ONNX Model ====
onnx_model_path = os.path.join(SCRIPT_DIR, "output_files", "scatter_elements.onnx")
onnx_model = onnx.load(onnx_model_path)
onnx.checker.check_model(onnx_model)
session = ort.InferenceSession(onnx_model_path)

# Default parameters
SIZE = 8
AXIS = 0

if len(sys.argv) >= 2:
    SIZE = int(sys.argv[1])

if len(sys.argv) >= 3:
    AXIS = int(sys.argv[2])

data_rows = SIZE
data_cols = SIZE
indices_rows = SIZE // 2
indices_cols = SIZE

print(f"\nScatterElements on {data_rows}x{data_cols} data, axis={AXIS}")

# Load matrices (generated by C++ code)
data = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/data.bin"), dtype=np.float32).reshape(data_rows, data_cols)
indices = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/indices.bin"), dtype=np.int64).reshape(indices_rows, indices_cols)
updates = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/updates.bin"), dtype=np.float32).reshape(indices_rows, indices_cols)

# ==== ONNX Golden Reference (using ONNXRuntime) ====
input_names = [input.name for input in onnx_model.graph.input]
onnx_ref = session.run(None, {
    input_names[0]: data,
    input_names[1]: indices,
    input_names[2]: updates
})[0]

# ==== C Scalar ====
c_scalar = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/scatter_scalar.bin"), dtype=np.float32).reshape(data_rows, data_cols)

# ==== C Tiled Scalar ====
c_tiled_scalar = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/scatter_tiled_scalar.bin"), dtype=np.float32).reshape(data_rows, data_cols)

# ==== C Vectorized (e32mx) ====
c_e32m1 = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/scatter_e32m1.bin"), dtype=np.float32).reshape(data_rows, data_cols)
c_e32m2 = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/scatter_e32m2.bin"), dtype=np.float32).reshape(data_rows, data_cols)
c_e32m4 = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/scatter_e32m4.bin"), dtype=np.float32).reshape(data_rows, data_cols)
c_e32m8 = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/scatter_e32m8.bin"), dtype=np.float32).reshape(data_rows, data_cols)

# ==== C Tiled Vectorized (e32mx) ====
c_tiled_e32m1 = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/scatter_tiled_e32m1.bin"), dtype=np.float32).reshape(data_rows, data_cols)
c_tiled_e32m2 = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/scatter_tiled_e32m2.bin"), dtype=np.float32).reshape(data_rows, data_cols)
c_tiled_e32m4 = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/scatter_tiled_e32m4.bin"), dtype=np.float32).reshape(data_rows, data_cols)
c_tiled_e32m8 = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/scatter_tiled_e32m8.bin"), dtype=np.float32).reshape(data_rows, data_cols)

# ONNX --> golden reference
c_ref = onnx_ref

# ==== Results Table ====
implementations = [
    ("ONNX Golden Ref", onnx_ref),
    ("C Scalar", c_scalar),
    ("C Tiled Scalar", c_tiled_scalar),
    ("C Vectorized (e32m1)", c_e32m1),
    ("C Vectorized (e32m2)", c_e32m2),
    ("C Vectorized (e32m4)", c_e32m4),
    ("C Vectorized (e32m8)", c_e32m8),
    ("C Tiled Vectorized (e32m1)", c_tiled_e32m1),
    ("C Tiled Vectorized (e32m2)", c_tiled_e32m2),
    ("C Tiled Vectorized (e32m4)", c_tiled_e32m4),
    ("C Tiled Vectorized (e32m8)", c_tiled_e32m8),  
]

print(f"\n{'Implementation':<30}{'Max Abs Error':<20}{'SNR (dB)':<20}")
print("-" * 70)

for name, result in implementations:
    mae = max_abs_error(c_ref, result)
    snr = snr_db(c_ref, result)
    print(f"{name:<30}{mae:<20.6g}{snr:<20.6g}")

