import numpy as np
import onnx
from onnx import helper, TensorProto
import onnxruntime as ort
import sys
import os

# Get the absolute path to the script's directory
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# =============== Import Utility Functions ===============
from src.onnx_utils import max_abs_error, snr_db

# Default parameters
SIZE = 8
AXIS = 0

if len(sys.argv) >= 2:
    SIZE = int(sys.argv[1])

if len(sys.argv) >= 3:
    AXIS = int(sys.argv[2])

data_rows = SIZE
data_cols = SIZE
indices_rows = SIZE // 2
indices_cols = SIZE

print(f"\nGather on {data_rows}x{data_cols} data, axis={AXIS}")

# ==== Create ONNX Model Dynamically Based on AXIS ====
data_tensor = helper.make_tensor_value_info("data", TensorProto.FLOAT, [None, None])
indices_tensor = helper.make_tensor_value_info("indices", TensorProto.INT64, [None, None])
output_tensor = helper.make_tensor_value_info("output", TensorProto.FLOAT, [None, None])

gather_node = helper.make_node(
    "GatherElements",
    inputs=["data", "indices"],
    outputs=["output"],
    axis=AXIS
)

graph = helper.make_graph(
    nodes=[gather_node],
    name="GatherGraph",
    inputs=[data_tensor, indices_tensor],
    outputs=[output_tensor]
)

model = helper.make_model(graph, producer_name="gather_test", opset_imports=[helper.make_opsetid("", 13)])
model.ir_version = 7

# Create session from the model
session = ort.InferenceSession(model.SerializeToString())

# Load matrices (generated by C++ code)
data = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/data.bin"), dtype=np.float32).reshape(data_rows, data_cols)
indices = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/indices.bin"), dtype=np.int64).reshape(indices_rows, indices_cols)

# ==== ONNX Golden Reference (using ONNXRuntime) ====
onnx_ref = session.run(None, {
    "data": data,
    "indices": indices
})[0]

# ==== C outputs ====
c_scalar = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/gather_scalar.bin"), dtype=np.float32).reshape(indices_rows, indices_cols)
c_tiled_scalar = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/gather_tiled_scalar.bin"), dtype=np.float32).reshape(indices_rows, indices_cols)
c_e32m1 = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/gather_e32m1.bin"), dtype=np.float32).reshape(indices_rows, indices_cols)
c_tiled_e32m1 = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/gather_tiled_e32m1.bin"), dtype=np.float32).reshape(indices_rows, indices_cols)
c_e32m2 = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/gather_e32m2.bin"), dtype=np.float32).reshape(indices_rows, indices_cols)
c_e32m4 = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/gather_e32m4.bin"), dtype=np.float32).reshape(indices_rows, indices_cols)
c_e32m8 = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/gather_e32m8.bin"), dtype=np.float32).reshape(indices_rows, indices_cols)
c_tiled_e32m2 = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/gather_tiled_e32m2.bin"), dtype=np.float32).reshape(indices_rows, indices_cols)
c_tiled_e32m4 = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/gather_tiled_e32m4.bin"), dtype=np.float32).reshape(indices_rows, indices_cols)
c_tiled_e32m8 = np.fromfile(os.path.join(SCRIPT_DIR, "./output_files/gather_tiled_e32m8.bin"), dtype=np.float32).reshape(indices_rows, indices_cols)

# ==== Results Table ====
implementations = [
    ("ONNX Golden Ref", onnx_ref),
    ("C Scalar", c_scalar),
    ("C Tiled Scalar", c_tiled_scalar),
    ("C Vectorized (e32m1)", c_e32m1),
    ("C Vectorized (e32m2)", c_e32m2),
    ("C Vectorized (e32m4)", c_e32m4),
    ("C Vectorized (e32m8)", c_e32m8),
    ("C Tiled Vectorized (e32m1)", c_tiled_e32m1),
    ("C Tiled Vectorized (e32m2)", c_tiled_e32m2),
    ("C Tiled Vectorized (e32m4)", c_tiled_e32m4),
    ("C Tiled Vectorized (e32m8)", c_tiled_e32m8),
]

print(f"\n{'Implementation':<30}{'Max Abs Error':<20}{'SNR (dB)':<20}")
print("-" * 70)

for name, result in implementations:
    mae = max_abs_error(onnx_ref, result)
    snr = snr_db(onnx_ref, result)
    print(f"{name:<30}{mae:<20.6g}{snr:<20.6g}")

